name: 🐛 Bug Report
description: Report a bug to help us improve.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below.
  - type: textarea
    id: bug-description
    attributes:
      label: Description
      description: Provide a clear and concise description of what the bug is.
      placeholder: "Example: The login button stays disabled even after entering credentials."
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Screenshots / Context
      description: Add screenshots, logs, or any other context about the problem here.
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Docker Setup
        - Manual Installation
        - Live-Demo
    validations:
      required: true
